diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index 8d3b969f8965b..c12e61cab2e5f 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -2022,6 +2022,32 @@ enum HistogramValue {
   AUTOFILLPRIVATE_GETREQUIREDATTRIBUTETYPESFORENTITYTYPENAME = 1959,
   PDFVIEWERPRIVATE_GLICSUMMARIZE = 1960,
   GLICPRIVATE_GETSTATE = 1961,
+  // Wayfinder: extension function histogram values
+  DELETED_WAYFINDER_GETACCESSIBILITYTREE = 1962,
+  DELETED_WAYFINDER_GETINTERACTIVESNAPSHOT = 1963,
+  DELETED_WAYFINDER_CLICK = 1964,
+  DELETED_WAYFINDER_INPUTTEXT = 1965,
+  DELETED_WAYFINDER_CLEAR = 1966,
+  WAYFINDER_GETPAGELOADSTATUS = 1967,
+  DELETED_WAYFINDER_SCROLLUP = 1968,
+  DELETED_WAYFINDER_SCROLLDOWN = 1969,
+  DELETED_WAYFINDER_SCROLLTONODE = 1970,
+  DELETED_WAYFINDER_SENDKEYS = 1971,
+  WAYFINDER_GETPAGESTRUCTURE = 1972,
+  DELETED_WAYFINDER_CAPTURESCREENSHOT = 1973,
+  DELETED_WAYFINDER_GETSNAPSHOT = 1974,
+  WAYFINDER_GETPREF = 1975,
+  WAYFINDER_SETPREF = 1976,
+  WAYFINDER_GETALLPREFS = 1977,
+  WAYFINDER_LOGMETRIC = 1978,
+  WAYFINDER_GETVERSIONNUMBER = 1979,
+  WAYFINDER_EXECUTEJAVASCRIPT = 1980,
+  WAYFINDER_CLICKCOORDINATES = 1981,
+  WAYFINDER_TYPEATCOORDINATES = 1982,
+  SIDEPANEL_WAYFINDERTOGGLE = 1983,
+  SIDEPANEL_WAYFINDERISOPEN = 1984,
+  WAYFINDER_GETWAYFINDERVERSIONNUMBER = 1985,
+  WAYFINDER_CHOOSEPATH = 1986,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
